In [35]:
pip install sqlalchemy mysql-connector-python pandas

Requirement already satisfied: sqlalchemy in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (2.0.47)
Requirement already satisfied: mysql-connector-python in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (9.6.0)
Requirement already satisfied: pandas in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.0.1)
Requirement already satisfied: greenlet>=1 in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=2.3.3 in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [36]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [59]:
pip install cryptography  pymysql

Requirement already satisfied: cryptography in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (46.0.5)
Requirement already satisfied: pymysql in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (1.1.2)
Requirement already satisfied: cffi>=2.0.0 in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from cryptography) (2.0.0)
Requirement already satisfied: pycparser in c:\users\hp\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from cffi>=2.0.0->cryptography) (2.23)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [2]:
import os
import requests as rq
import json
import pandas as pd
import pymysql
from sqlalchemy import create_engine
from dotenv import load_dotenv

In [3]:
api="http://api.football-data.org/v4/competitions"
api_Key="e088f77b0f8045c79715fe7fc1e961ab"

In [4]:
season:2021
querystring={"season":2021}

In [5]:
headers={
"X-Auth-Token": "e088f77b0f8045c79715fe7fc1e961ab"}

In [73]:
base_url=rq.get(url=api,headers=headers)

In [88]:
data=base_url.json()
print(data)

{'count': 13, 'filters': {'client': 'Kanak Sharma'}, 'competitions': [{'id': 2013, 'area': {'id': 2032, 'name': 'Brazil', 'code': 'BRA', 'flag': 'https://crests.football-data.org/764.svg'}, 'name': 'Campeonato Brasileiro Série A', 'code': 'BSA', 'type': 'LEAGUE', 'emblem': 'https://crests.football-data.org/bsa.png', 'plan': 'TIER_ONE', 'currentSeason': {'id': 2474, 'startDate': '2026-01-28', 'endDate': '2026-12-02', 'currentMatchday': 4, 'winner': None}, 'numberOfAvailableSeasons': 10, 'lastUpdated': '2024-09-13T16:55:53Z'}, {'id': 2016, 'area': {'id': 2072, 'name': 'England', 'code': 'ENG', 'flag': 'https://crests.football-data.org/770.svg'}, 'name': 'Championship', 'code': 'ELC', 'type': 'LEAGUE', 'emblem': 'https://crests.football-data.org/ELC.png', 'plan': 'TIER_ONE', 'currentSeason': {'id': 2416, 'startDate': '2025-08-08', 'endDate': '2026-12-29', 'currentMatchday': 35, 'winner': None}, 'numberOfAvailableSeasons': 9, 'lastUpdated': '2024-09-13T16:51:18Z'}, {'id': 2021, 'area': {'id': 2072, 'name': 'England', 'code': 'ENG', 'flag': 'https://crests.football-data.org/770.svg'}, 'name': 'Premier League', 'code': 'PL', 'type': 'LEAGUE', 'emblem': 'https://crests.football-data.org/PL.png', 'plan': 'TIER_ONE', 'currentSeason': {'id': 2403, 'startDate': '2025-08-15', 'endDate': '2026-05-24', 'currentMatchday': 31, 'winner': None}, 'numberOfAvailableSeasons': 127, 'lastUpdated': '2024-09-13T16:51:24Z'}, {'id': 2001, 'area': {'id': 2077, 'name': 'Europe', 'code': 'EUR', 'flag': 'https://crests.football-data.org/EUR.svg'}, 'name': 'UEFA Champions League', 'code': 'CL', 'type': 'CUP', 'emblem': 'https://crests.football-data.org/CL.png', 'plan': 'TIER_ONE', 'currentSeason': {'id': 2454, 'startDate': '2025-09-16', 'endDate': '2026-05-30', 'currentMatchday': 8, 'winner': None}, 'numberOfAvailableSeasons': 46, 'lastUpdated': '2024-09-13T16:53:48Z'}, {'id': 2018, 'area': {'id': 2077, 'name': 'Europe', 'code': 'EUR', 'flag': 'https://crests.football-data.org/EUR.svg'}, 'name': 'European Championship', 'code': 'EC', 'type': 'CUP', 'emblem': 'https://crests.football-data.org/ec.png', 'plan': 'TIER_ONE', 'currentSeason': {'id': 1537, 'startDate': '2024-06-14', 'endDate': '2024-07-14', 'currentMatchday': 7, 'winner': {'id': 760, 'name': 'Spain', 'shortName': 'Spain', 'tla': 'ESP', 'crest': 'https://crests.football-data.org/760.svg', 'address': 'Ramón y Cajal, s/n Las Rozas 28230', 'website': 'http://www.rfef.es', 'founded': 1909, 'clubColors': 'Red / Blue / Yellow', 'venue': 'Estadio Alfredo Di Stéfano', 'lastUpdated': '2021-05-26T09:46:48Z'}}, 'numberOfAvailableSeasons': 17, 'lastUpdated': '2024-09-13T17:04:30Z'}, {'id': 2015, 'area': {'id': 2081, 'name': 'France', 'code': 'FRA', 'flag': 'https://crests.football-data.org/773.svg'}, 'name': 'Ligue 1', 'code': 'FL1', 'type': 'LEAGUE', 'emblem': 'https://crests.football-data.org/FL1.png', 'plan': 'TIER_ONE', 'currentSeason': {'id': 2420, 'startDate': '2025-08-17', 'endDate': '2026-05-16', 'currentMatchday': 24, 'winner': None}, 'numberOfAvailableSeasons': 82, 'lastUpdated': '2024-09-13T16:49:18Z'}, {'id': 2002, 'area': {'id': 2088, 'name': 'Germany', 'code': 'DEU', 'flag': 'https://crests.football-data.org/759.svg'}, 'name': 'Bundesliga', 'code': 'BL1', 'type': 'LEAGUE', 'emblem': 'https://crests.football-data.org/BL1.png', 'plan': 'TIER_ONE', 'currentSeason': {'id': 2414, 'startDate': '2025-08-22', 'endDate': '2026-05-16', 'currentMatchday': 24, 'winner': None}, 'numberOfAvailableSeasons': 63, 'lastUpdated': '2024-09-13T16:48:00Z'}, {'id': 2019, 'area': {'id': 2114, 'name': 'Italy', 'code': 'ITA', 'flag': 'https://crests.football-data.org/784.svg'}, 'name': 'Serie A', 'code': 'SA', 'type': 'LEAGUE', 'emblem': 'https://crests.football-data.org/c111.png', 'plan': 'TIER_ONE', 'currentSeason': {'id': 2395, 'startDate': '2025-08-24', 'endDate': '2026-05-24', 'currentMatchday': 27, 'winner': None}, 'numberOfAvailableSeasons': 94, 'lastUpdated': '2026-01-02T11:22:51Z'}, {'id': 2003, 'area': {'id': 2163, 'name': 'Netherlands', 'code': 'NLD', 'flag': 'https://crests.football-data.org/8601.svg'}, 'name': 'Eredivisie', 'code': 'DED', 'type': 'LEAGUE', 'emblem': 'https://crests.football-data.org/ED.png', 'plan': 'TIER_ONE', 'currentSeason': {'id': 2400, 'startDate': '2025-08-08', 'endDate': '2026-05-17', 'currentMatchday': 25, 'winner': None}, 'numberOfAvailableSeasons': 70, 'lastUpdated': '2024-09-13T16:34:42Z'}, {'id': 2017, 'area': {'id': 2187, 'name': 'Portugal', 'code': 'POR', 'flag': 'https://crests.football-data.org/765.svg'}, 'name': 'Primeira Liga', 'code': 'PPL', 'type': 'LEAGUE', 'emblem': 'https://crests.football-data.org/PPL.png', 'plan': 'TIER_ONE', 'currentSeason': {'id': 2433, 'startDate': '2025-08-08', 'endDate': '2026-05-17', 'currentMatchday': 24, 'winner': None}, 'numberOfAvailableSeasons': 77, 'lastUpdated': '2024-09-13T16:54:08Z'}, {'id': 2152, 'area': {'id': 2220, 'name': 'South America', 'code': 'SAM', 'flag': 'https://crests.football-data.org/CLI.svg'}, 'name': 'Copa Libertadores', 'code': 'CLI', 'type': 'CUP', 'emblem': 'https://crests.football-data.org/CLI.svg', 'plan': 'TIER_FOUR', 'currentSeason': {'id': 2466, 'startDate': '2026-02-05', 'endDate': '2026-02-26', 'currentMatchday': 2, 'winner': None}, 'numberOfAvailableSeasons': 6, 'lastUpdated': '2025-02-13T21:08:12Z'}, {'id': 2014, 'area': {'id': 2224, 'name': 'Spain', 'code': 'ESP', 'flag': 'https://crests.football-data.org/760.svg'}, 'name': 'Primera Division', 'code': 'PD', 'type': 'LEAGUE', 'emblem': 'https://crests.football-data.org/laliga.png', 'plan': 'TIER_ONE', 'currentSeason': {'id': 2429, 'startDate': '2025-08-17', 'endDate': '2026-05-24', 'currentMatchday': 26, 'winner': None}, 'numberOfAvailableSeasons': 95, 'lastUpdated': '2024-09-13T16:52:33Z'}, {'id': 2000, 'area': {'id': 2267, 'name': 'World', 'code': 'INT', 'flag': None}, 'name': 'FIFA World Cup', 'code': 'WC', 'type': 'CUP', 'emblem': 'https://crests.football-data.org/wm26.png', 'plan': 'TIER_ONE', 'currentSeason': {'id': 2398, 'startDate': '2026-06-11', 'endDate': '2026-07-19', 'currentMatchday': 1, 'winner': None}, 'numberOfAvailableSeasons': 23, 'lastUpdated': '2025-12-08T05:32:32Z'}]}

In [89]:
formatted_data=json.dumps(data,indent=4)
print(formatted_data)

{
    "count": 13,
    "filters": {
        "client": "Kanak Sharma"
    },
    "competitions": [
        {
            "id": 2013,
            "area": {
                "id": 2032,
                "name": "Brazil",
                "code": "BRA",
                "flag": "https://crests.football-data.org/764.svg"
            },
            "name": "Campeonato Brasileiro S\u00e9rie A",
            "code": "BSA",
            "type": "LEAGUE",
            "emblem": "https://crests.football-data.org/bsa.png",
            "plan": "TIER_ONE",
            "currentSeason": {
                "id": 2474,
                "startDate": "2026-01-28",
                "endDate": "2026-12-02",
                "currentMatchday": 4,
                "winner": null
            },
            "numberOfAvailableSeasons": 10,
            "lastUpdated": "2024-09-13T16:55:53Z"
        },
        {
            "id": 2016,
            "area": {
                "id": 2072,
                "name": "England",
                "code": "ENG",
                "flag": "https://crests.football-data.org/770.svg"
            },
            "name": "Championship",
            "code": "ELC",
            "type": "LEAGUE",
            "emblem": "https://crests.football-data.org/ELC.png",
            "plan": "TIER_ONE",
            "currentSeason": {
                "id": 2416,
                "startDate": "2025-08-08",
                "endDate": "2026-12-29",
                "currentMatchday": 35,
                "winner": null
            },
            "numberOfAvailableSeasons": 9,
            "lastUpdated": "2024-09-13T16:51:18Z"
        },
        {
            "id": 2021,
            "area": {
                "id": 2072,
                "name": "England",
                "code": "ENG",
                "flag": "https://crests.football-data.org/770.svg"
            },
            "name": "Premier League",
            "code": "PL",
            "type": "LEAGUE",
            "emblem": "https://crests.football-data.org/PL.png",
            "plan": "TIER_ONE",
            "currentSeason": {
                "id": 2403,
                "startDate": "2025-08-15",
                "endDate": "2026-05-24",
                "currentMatchday": 31,
                "winner": null
            },
            "numberOfAvailableSeasons": 127,
            "lastUpdated": "2024-09-13T16:51:24Z"
        },
        {
            "id": 2001,
            "area": {
                "id": 2077,
                "name": "Europe",
                "code": "EUR",
                "flag": "https://crests.football-data.org/EUR.svg"
            },
            "name": "UEFA Champions League",
            "code": "CL",
            "type": "CUP",
            "emblem": "https://crests.football-data.org/CL.png",
            "plan": "TIER_ONE",
            "currentSeason": {
                "id": 2454,
                "startDate": "2025-09-16",
                "endDate": "2026-05-30",
                "currentMatchday": 8,
                "winner": null
            },
            "numberOfAvailableSeasons": 46,
            "lastUpdated": "2024-09-13T16:53:48Z"
        },
        {
            "id": 2018,
            "area": {
                "id": 2077,
                "name": "Europe",
                "code": "EUR",
                "flag": "https://crests.football-data.org/EUR.svg"
            },
            "name": "European Championship",
            "code": "EC",
            "type": "CUP",
            "emblem": "https://crests.football-data.org/ec.png",
            "plan": "TIER_ONE",
            "currentSeason": {
                "id": 1537,
                "startDate": "2024-06-14",
                "endDate": "2024-07-14",
                "currentMatchday": 7,
                "winner": {
                    "id": 760,
                    "name": "Spain",
                    "shortName": "Spain",
                    "tla": "ESP",
                    "crest": "https://crests.football-data.org/760.svg",
                    "address": "Ram\u00f3n y Cajal, s/n Las Rozas 28230",
                    "website": "http://www.rfef.es",
                    "founded": 1909,
                    "clubColors": "Red / Blue / Yellow",
                    "venue": "Estadio Alfredo Di St\u00e9fano",
                    "lastUpdated": "2021-05-26T09:46:48Z"
                }
            },
            "numberOfAvailableSeasons": 17,
            "lastUpdated": "2024-09-13T17:04:30Z"
        },
        {
            "id": 2015,
            "area": {
                "id": 2081,
                "name": "France",
                "code": "FRA",
                "flag": "https://crests.football-data.org/773.svg"
            },
            "name": "Ligue 1",
            "code": "FL1",
            "type": "LEAGUE",
            "emblem": "https://crests.football-data.org/FL1.png",
            "plan": "TIER_ONE",
            "currentSeason": {
                "id": 2420,
                "startDate": "2025-08-17",
                "endDate": "2026-05-16",
                "currentMatchday": 24,
                "winner": null
            },
            "numberOfAvailableSeasons": 82,
            "lastUpdated": "2024-09-13T16:49:18Z"
        },
        {
            "id": 2002,
            "area": {
                "id": 2088,
                "name": "Germany",
                "code": "DEU",
                "flag": "https://crests.football-data.org/759.svg"
            },
            "name": "Bundesliga",
            "code": "BL1",
            "type": "LEAGUE",
            "emblem": "https://crests.football-data.org/BL1.png",
            "plan": "TIER_ONE",
            "currentSeason": {
                "id": 2414,
                "startDate": "2025-08-22",
                "endDate": "2026-05-16",
                "currentMatchday": 24,
                "winner": null
            },
            "numberOfAvailableSeasons": 63,
            "lastUpdated": "2024-09-13T16:48:00Z"
        },
        {
            "id": 2019,
            "area": {
                "id": 2114,
                "name": "Italy",
                "code": "ITA",
                "flag": "https://crests.football-data.org/784.svg"
            },
            "name": "Serie A",
            "code": "SA",
            "type": "LEAGUE",
            "emblem": "https://crests.football-data.org/c111.png",
            "plan": "TIER_ONE",
            "currentSeason": {
                "id": 2395,
                "startDate": "2025-08-24",
                "endDate": "2026-05-24",
                "currentMatchday": 27,
                "winner": null
            },
            "numberOfAvailableSeasons": 94,
            "lastUpdated": "2026-01-02T11:22:51Z"
        },
        {
            "id": 2003,
            "area": {
                "id": 2163,
                "name": "Netherlands",
                "code": "NLD",
                "flag": "https://crests.football-data.org/8601.svg"
            },
            "name": "Eredivisie",
            "code": "DED",
            "type": "LEAGUE",
            "emblem": "https://crests.football-data.org/ED.png",
            "plan": "TIER_ONE",
            "currentSeason": {
                "id": 2400,
                "startDate": "2025-08-08",
                "endDate": "2026-05-17",
                "currentMatchday": 25,
                "winner": null
            },
            "numberOfAvailableSeasons": 70,
            "lastUpdated": "2024-09-13T16:34:42Z"
        },
        {
            "id": 2017,
            "area": {
                "id": 2187,
                "name": "Portugal",
                "code": "POR",
                "flag": "https://crests.football-data.org/765.svg"
            },
            "name": "Primeira Liga",
            "code": "PPL",
            "type": "LEAGUE",
            "emblem": "https://crests.football-data.org/PPL.png",
            "plan": "TIER_ONE",
            "currentSeason": {
                "id": 2433,
                "startDate": "2025-08-08",
                "endDate": "2026-05-17",
                "currentMatchday": 24,
                "winner": null
            },
            "numberOfAvailableSeasons": 77,
            "lastUpdated": "2024-09-13T16:54:08Z"
        },
        {
            "id": 2152,
            "area": {
                "id": 2220,
                "name": "South America",
                "code": "SAM",
                "flag": "https://crests.football-data.org/CLI.svg"
            },
            "name": "Copa Libertadores",
            "code": "CLI",
            "type": "CUP",
            "emblem": "https://crests.football-data.org/CLI.svg",
            "plan": "TIER_FOUR",
            "currentSeason": {
                "id": 2466,
                "startDate": "2026-02-05",
                "endDate": "2026-02-26",
                "currentMatchday": 2,
                "winner": null
            },
            "numberOfAvailableSeasons": 6,
            "lastUpdated": "2025-02-13T21:08:12Z"
        },
        {
            "id": 2014,
            "area": {
                "id": 2224,
                "name": "Spain",
                "code": "ESP",
                "flag": "https://crests.football-data.org/760.svg"
            },
            "name": "Primera Division",
            "code": "PD",
            "type": "LEAGUE",
            "emblem": "https://crests.football-data.org/laliga.png",
            "plan": "TIER_ONE",
            "currentSeason": {
                "id": 2429,
                "startDate": "2025-08-17",
                "endDate": "2026-05-24",
                "currentMatchday": 26,
                "winner": null
            },
            "numberOfAvailableSeasons": 95,
            "lastUpdated": "2024-09-13T16:52:33Z"
        },
        {
            "id": 2000,
            "area": {
                "id": 2267,
                "name": "World",
                "code": "INT",
                "flag": null
            },
            "name": "FIFA World Cup",
            "code": "WC",
            "type": "CUP",
            "emblem": "https://crests.football-data.org/wm26.png",
            "plan": "TIER_ONE",
            "currentSeason": {
                "id": 2398,
                "startDate": "2026-06-11",
                "endDate": "2026-07-19",
                "currentMatchday": 1,
                "winner": null
            },
            "numberOfAvailableSeasons": 23,
            "lastUpdated": "2025-12-08T05:32:32Z"
        }
    ]
}

In [90]:
competitions=data["competitions"]
competitions

[{'id': 2013,
  'area': {'id': 2032,
   'name': 'Brazil',
   'code': 'BRA',
   'flag': 'https://crests.football-data.org/764.svg'},
  'name': 'Campeonato Brasileiro Série A',
  'code': 'BSA',
  'type': 'LEAGUE',
  'emblem': 'https://crests.football-data.org/bsa.png',
  'plan': 'TIER_ONE',
  'currentSeason': {'id': 2474,
   'startDate': '2026-01-28',
   'endDate': '2026-12-02',
   'currentMatchday': 4,
   'winner': None},
  'numberOfAvailableSeasons': 10,
  'lastUpdated': '2024-09-13T16:55:53Z'},
 {'id': 2016,
  'area': {'id': 2072,
   'name': 'England',
   'code': 'ENG',
   'flag': 'https://crests.football-data.org/770.svg'},
  'name': 'Championship',
  'code': 'ELC',
  'type': 'LEAGUE',
  'emblem': 'https://crests.football-data.org/ELC.png',
  'plan': 'TIER_ONE',
  'currentSeason': {'id': 2416,
   'startDate': '2025-08-08',
   'endDate': '2026-12-29',
   'currentMatchday': 35,
   'winner': None},
  'numberOfAvailableSeasons': 9,
  'lastUpdated': '2024-09-13T16:51:18Z'},
 {'id': 2021,
  'area': {'id': 2072,
   'name': 'England',
   'code': 'ENG',
   'flag': 'https://crests.football-data.org/770.svg'},
  'name': 'Premier League',
  'code': 'PL',
  'type': 'LEAGUE',
  'emblem': 'https://crests.football-data.org/PL.png',
  'plan': 'TIER_ONE',
  'currentSeason': {'id': 2403,
   'startDate': '2025-08-15',
   'endDate': '2026-05-24',
   'currentMatchday': 31,
   'winner': None},
  'numberOfAvailableSeasons': 127,
  'lastUpdated': '2024-09-13T16:51:24Z'},
 {'id': 2001,
  'area': {'id': 2077,
   'name': 'Europe',
   'code': 'EUR',
   'flag': 'https://crests.football-data.org/EUR.svg'},
  'name': 'UEFA Champions League',
  'code': 'CL',
  'type': 'CUP',
  'emblem': 'https://crests.football-data.org/CL.png',
  'plan': 'TIER_ONE',
  'currentSeason': {'id': 2454,
   'startDate': '2025-09-16',
   'endDate': '2026-05-30',
   'currentMatchday': 8,
   'winner': None},
  'numberOfAvailableSeasons': 46,
  'lastUpdated': '2024-09-13T16:53:48Z'},
 {'id': 2018,
  'area': {'id': 2077,
   'name': 'Europe',
   'code': 'EUR',
   'flag': 'https://crests.football-data.org/EUR.svg'},
  'name': 'European Championship',
  'code': 'EC',
  'type': 'CUP',
  'emblem': 'https://crests.football-data.org/ec.png',
  'plan': 'TIER_ONE',
  'currentSeason': {'id': 1537,
   'startDate': '2024-06-14',
   'endDate': '2024-07-14',
   'currentMatchday': 7,
   'winner': {'id': 760,
    'name': 'Spain',
    'shortName': 'Spain',
    'tla': 'ESP',
    'crest': 'https://crests.football-data.org/760.svg',
    'address': 'Ramón y Cajal, s/n Las Rozas 28230',
    'website': 'http://www.rfef.es',
    'founded': 1909,
    'clubColors': 'Red / Blue / Yellow',
    'venue': 'Estadio Alfredo Di Stéfano',
    'lastUpdated': '2021-05-26T09:46:48Z'}},
  'numberOfAvailableSeasons': 17,
  'lastUpdated': '2024-09-13T17:04:30Z'},
 {'id': 2015,
  'area': {'id': 2081,
   'name': 'France',
   'code': 'FRA',
   'flag': 'https://crests.football-data.org/773.svg'},
  'name': 'Ligue 1',
  'code': 'FL1',
  'type': 'LEAGUE',
  'emblem': 'https://crests.football-data.org/FL1.png',
  'plan': 'TIER_ONE',
  'currentSeason': {'id': 2420,
   'startDate': '2025-08-17',
   'endDate': '2026-05-16',
   'currentMatchday': 24,
   'winner': None},
  'numberOfAvailableSeasons': 82,
  'lastUpdated': '2024-09-13T16:49:18Z'},
 {'id': 2002,
  'area': {'id': 2088,
   'name': 'Germany',
   'code': 'DEU',
   'flag': 'https://crests.football-data.org/759.svg'},
  'name': 'Bundesliga',
  'code': 'BL1',
  'type': 'LEAGUE',
  'emblem': 'https://crests.football-data.org/BL1.png',
  'plan': 'TIER_ONE',
  'currentSeason': {'id': 2414,
   'startDate': '2025-08-22',
   'endDate': '2026-05-16',
   'currentMatchday': 24,
   'winner': None},
  'numberOfAvailableSeasons': 63,
  'lastUpdated': '2024-09-13T16:48:00Z'},
 {'id': 2019,
  'area': {'id': 2114,
   'name': 'Italy',
   'code': 'ITA',
   'flag': 'https://crests.football-data.org/784.svg'},
  'name': 'Serie A',
  'code': 'SA',
  'type': 'LEAGUE',
  'emblem': 'https://crests.football-data.org/c111.png',
  'plan': 'TIER_ONE',
  'currentSeason': {'id': 2395,
   'startDate': '2025-08-24',
   'endDate': '2026-05-24',
   'currentMatchday': 27,
   'winner': None},
  'numberOfAvailableSeasons': 94,
  'lastUpdated': '2026-01-02T11:22:51Z'},
 {'id': 2003,
  'area': {'id': 2163,
   'name': 'Netherlands',
   'code': 'NLD',
   'flag': 'https://crests.football-data.org/8601.svg'},
  'name': 'Eredivisie',
  'code': 'DED',
  'type': 'LEAGUE',
  'emblem': 'https://crests.football-data.org/ED.png',
  'plan': 'TIER_ONE',
  'currentSeason': {'id': 2400,
   'startDate': '2025-08-08',
   'endDate': '2026-05-17',
   'currentMatchday': 25,
   'winner': None},
  'numberOfAvailableSeasons': 70,
  'lastUpdated': '2024-09-13T16:34:42Z'},
 {'id': 2017,
  'area': {'id': 2187,
   'name': 'Portugal',
   'code': 'POR',
   'flag': 'https://crests.football-data.org/765.svg'},
  'name': 'Primeira Liga',
  'code': 'PPL',
  'type': 'LEAGUE',
  'emblem': 'https://crests.football-data.org/PPL.png',
  'plan': 'TIER_ONE',
  'currentSeason': {'id': 2433,
   'startDate': '2025-08-08',
   'endDate': '2026-05-17',
   'currentMatchday': 24,
   'winner': None},
  'numberOfAvailableSeasons': 77,
  'lastUpdated': '2024-09-13T16:54:08Z'},
 {'id': 2152,
  'area': {'id': 2220,
   'name': 'South America',
   'code': 'SAM',
   'flag': 'https://crests.football-data.org/CLI.svg'},
  'name': 'Copa Libertadores',
  'code': 'CLI',
  'type': 'CUP',
  'emblem': 'https://crests.football-data.org/CLI.svg',
  'plan': 'TIER_FOUR',
  'currentSeason': {'id': 2466,
   'startDate': '2026-02-05',
   'endDate': '2026-02-26',
   'currentMatchday': 2,
   'winner': None},
  'numberOfAvailableSeasons': 6,
  'lastUpdated': '2025-02-13T21:08:12Z'},
 {'id': 2014,
  'area': {'id': 2224,
   'name': 'Spain',
   'code': 'ESP',
   'flag': 'https://crests.football-data.org/760.svg'},
  'name': 'Primera Division',
  'code': 'PD',
  'type': 'LEAGUE',
  'emblem': 'https://crests.football-data.org/laliga.png',
  'plan': 'TIER_ONE',
  'currentSeason': {'id': 2429,
   'startDate': '2025-08-17',
   'endDate': '2026-05-24',
   'currentMatchday': 26,
   'winner': None},
  'numberOfAvailableSeasons': 95,
  'lastUpdated': '2024-09-13T16:52:33Z'},
 {'id': 2000,
  'area': {'id': 2267, 'name': 'World', 'code': 'INT', 'flag': None},
  'name': 'FIFA World Cup',
  'code': 'WC',
  'type': 'CUP',
  'emblem': 'https://crests.football-data.org/wm26.png',
  'plan': 'TIER_ONE',
  'currentSeason': {'id': 2398,
   'startDate': '2026-06-11',
   'endDate': '2026-07-19',
   'currentMatchday': 1,
   'winner': None},
  'numberOfAvailableSeasons': 23,
  'lastUpdated': '2025-12-08T05:32:32Z'}]

In [91]:
competitions[1]

{'id': 2016,
 'area': {'id': 2072,
  'name': 'England',
  'code': 'ENG',
  'flag': 'https://crests.football-data.org/770.svg'},
 'name': 'Championship',
 'code': 'ELC',
 'type': 'LEAGUE',
 'emblem': 'https://crests.football-data.org/ELC.png',
 'plan': 'TIER_ONE',
 'currentSeason': {'id': 2416,
  'startDate': '2025-08-08',
  'endDate': '2026-12-29',
  'currentMatchday': 35,
  'winner': None},
 'numberOfAvailableSeasons': 9,
 'lastUpdated': '2024-09-13T16:51:18Z'}

In [92]:
column_name=data["competitions"][2]['area']
column_name

{'id': 2072,
 'name': 'England',
 'code': 'ENG',
 'flag': 'https://crests.football-data.org/770.svg'}

In [93]:
column=[ i for i in column_name]
print(column)

['id', 'name', 'code', 'flag']

In [94]:
df=pd.DataFrame(columns=column)

In [95]:
df

Empty DataFrame
Columns: [id, name, code, flag]
Index: []

In [96]:
length=len(data["competitions"])
print(length)

13

In [97]:
for i in range (0,12):
 column_data=[competitions[i]['area'][j] for j in competitions[i]['area']]
 length=len(df)
 df.loc[length]=column_data

In [98]:
df

      id           name code                                       flag
0   2032         Brazil  BRA   https://crests.football-data.org/764.svg
1   2072        England  ENG   https://crests.football-data.org/770.svg
2   2072        England  ENG   https://crests.football-data.org/770.svg
3   2077         Europe  EUR   https://crests.football-data.org/EUR.svg
4   2077         Europe  EUR   https://crests.football-data.org/EUR.svg
5   2081         France  FRA   https://crests.football-data.org/773.svg
6   2088        Germany  DEU   https://crests.football-data.org/759.svg
7   2114          Italy  ITA   https://crests.football-data.org/784.svg
8   2163    Netherlands  NLD  https://crests.football-data.org/8601.svg
9   2187       Portugal  POR   https://crests.football-data.org/765.svg
10  2220  South America  SAM   https://crests.football-data.org/CLI.svg
11  2224          Spain  ESP   https://crests.football-data.org/760.svg

In [99]:
MYSQL_HOST="localhost"
MYSQL_PORT="3306"
MYSQL_USER="root"
MYSQL_PASSWORD="Root_23"
MYSQL_DATABASE="football_database"

In [100]:
connection_url=f"mysql+mysqlconnector://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DATABASE}"

In [101]:
engine=create_engine(connection_url)
print("completed")

completed

In [102]:
connection_url="mysql+pymysql://root:Root_123@localhost/football_database"  
#charset=utf8mb4"
engine=create_engine(connection_url)
#,connect_args={'auth_plugin': 'mysql_native_password'})
try:
 df.to_sql("standings",
 con=engine,
 if_exists="replace", 
 index=False)
 print(" Data loaded")
except Exception as e:
 print(f"Error: {e}")

 Data loaded